### ISSUE TITLE
Standarize CircleCI environments

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#407]
When you try to run circleCI on a fork of any ernestio repository you will get an error on make deps, as the current repo is not deployed to the correct path, is on `whatever/reponame` instead of `ernestio/reponame`.

In order to fix this we will need, in a first instance, to move the repo to a valid location, so its independant of the user is executing the build.

You can find an example on how to do it on [ernestio/logger](https://github.com/ernestio/logger/blob/develop/circle.yml) which is basically doing:

```
machine:
  environment:
    ROOTPATH: /home/ubuntu/.go_workspace/src/github.com/ernestio

dependencies:
  pre:
    - mkdir -p $ROOTPATH/
    - rm -rf $ROOTPATH/logger
    - cp -R /home/ubuntu/logger $ROOTPATH/logger
    - cd $ROOTPATH/logger/ && make dev-deps
    - rm -rf $ROOTPATH/toolset/ && git clone git@github.com:ernestio/toolset.git $ROOTPATH/toolset/
    - cd $ROOTPATH/toolset/ernestci/ && bundle install

test:
  override:
    - cd $ROOTPATH/logger/ && make test
    - ruby $ROOTPATH/toolset/ernestci/run.rb .ernest-ci
    - cd $ROOTPATH/logger/ && make lint
```

In order to allow community work with our CI we will need to apply this to the active repos:

- [ ] definition-mapper
- [ ] api-gateway
- [ ] config-store
- [ ] monit
- [ ] user-store
- [ ] group-store
- [ ] datacenter-store
- [ ] service-store
- [ ] usage-store
- [ ] scheduler
- [ ] all-all-fake-connector
- [ ] logger
- [ ] ernest-cli
