### ISSUE TITLE
Load balancers with public ip error

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#480]
a yaml like:
```
    loadbalancers:
      - name: lb1
        frontend_ip_configurations:
          - name: fic1
            public_ip_address: config_2
```
will produce an error like:
```
ernest-cli service apply ~/Documents/tom.yml
Environment creation requested
Ernest will show you all output from your requested service creation
You can cancel at any moment with Ctrl+C, even the service is still being created, you won't have any output
Applying you definition
 Created Loadbalancer lb1
   Status    : errored
   Error     : Error creating the requested resource : Error Creating/Updating LoadBalancer network.LoadBalancersClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FrontendIPConfigHasNoSubnetOrPublicIP" Message="Frontend IP Configuration /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/rg2_tom/providers/Microsoft.Network/loadBalancers/lb1/frontendIPConfigurations/fic1 must reference either a Subnet or a Public IP Address." Details=[]
```
