### ISSUE TITLE
Storage account not being enctypted

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#487]
For a yaml like:
```
name: demo-tom-30
datacenter: demo13

resource_groups:
  - name: rg3_tom3
    location: eastus
    tags:
      environment: staging

    storage_accounts:
      - name: safest12354tom3
        account_type: Standard_LRS
        account_kind: Storage
        enable_blob_encyption: true
        containers:
          - name: scfestlatom3
            access_type: private
        tags:
          environment: staging

      - name: safest12354tom31
        account_type: Standard_LRS
        account_kind: BlobStorage
        enable_blob_encyption: true
        containers:
          - name: scfestlatom31
            access_type: private
        tags:
          environment: staging
```
Storage account doesn't seem to be properly encrypted based on option `enable_blob_encyption`
