### ISSUE TITLE
SQL database tags

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#490]
Given a yaml like

```
name: demo-tom-10
datacenter: demo13

resource_groups:
  - name: rg2_tom
    location: eastus
    tags:
      environment: staging

    sql_servers:
      - name: ernestserver02tom
        version: "12.0"
        administrator_login: mradministrator
        administrator_login_password: P4ssw0rd
        databases:
          - name: mydb
            max_size_bytes: "214748364800"
            restore_point_in_time: 2013-11-08T22:00:40Z
            requested_service_objective_name: S0
            restore_point_in_time: 2013-11-08T22:00:40Z
            tags:
              environment: staging
        rules:
          - name: rule1
            start_ip_address: 10.0.17.62
            end_ip_address: 10.0.17.63
```

specified tags are not being saved to azure.
