### ISSUE TITLE
Loadbalancers and tags

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#492]
Given i submit a yaml like:
```
name: demo-tom-40
datacenter: demo13

resource_groups:
  - name: rg2_tomX
    location: eastus
    tags:
      environment: staging

    virtual_networks:
      - name: vn_test_tom_X
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: sub_test_tom_X
            address_prefix: 10.0.1.0/24

    loadbalancers:
     - name: lbX
       frontend_ip_configurations:
         - name: fic1
           subnet: sub_test_tom_X
       tags:
         - environment: production
```

Provided tags are not being stored on azure.
