### ISSUE TITLE
Dependency issue when creating additional Security Groups

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#498]
There seems to be a dependency issue when creating additional Security Groups and Virtual Networks.

When applying:

```
name: azure-security-group
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    virtual_networks:
      - name: myNet
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: mySubnet
            address_prefix: 10.0.0.0/24
            security_group: mySG

    security_groups:
      - name: mySG
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535

```

Followed by:

```
name: azure-security-group
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    virtual_networks:
      - name: myNet
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: mySubnet
            address_prefix: 10.0.0.0/24
            security_group: mySG
          - name: mySubnet2
            address_prefix: 10.0.1.0/24
            security_group: mySG2
 
    security_groups:
      - name: mySG
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535
      - name: mySG2
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535
```

I receive:

```
Applying your definition
 Created Subnet mySubnet2
   Address Prefix : 10.0.1.0/24
   Status : errored
   Error     : Error creating the requested resource : network.SubnetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LinkedInvalidPropertyId" Message="Property id '$(components.#[_component_id=\"security_group::mySG2\"].id)' at path 'properties.networkSecurityGroup.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

Oops! Something went wrong. Please manually fix any errors shown above and re-apply your definition.
```

The Security Group gets created but the Virtual Network doesn't. Seems to be fail when trying to lookup the Security Group ID in order to assign it to the new Virtual Network. Reapplying the manifest after the failure results in a successful apply (with both Virtual Network and Security Group created as expected).

NATS error
```
service.create.error {"id":"cef27857-5575-4e4b-6ef9-7412341e21ee-b0b4a4fa9b1b08dd6de24a84f3a99b82","action":"service.create","components":[{"_action":"create","_component":"resource_group","_component_id":"resource_group::myRG","_provider":"azure","_state":"completed","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"datacenter_name":"","datacenter_region":"","datacenter_type":"","environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG","location":"eastus","name":"myRG","service":"68d69786-ca5e-4b15-58bd-c58e051c9a12-b0b4a4fa9b1b08dd6de24a84f3a99b82","tags":null},{"_action":"create","_component":"security_group","_component_id":"security_group::mySG","_provider":"azure","_state":"completed","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"datacenter_name":"","datacenter_region":"","datacenter_type":"","environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mySG","location":"eastus","name":"mySG","resource_group_name":"myRG","security_rules":[{"access":"Allow","description":"myRule","destination_address_prefix":"Internet","destination_port_range":"0-65535","direction":"Outbound","name":"myRule","priority":100,"protocol":"Tcp","source_address_prefix":"VirtualNetwork","source_port_range":"*"}],"service":"68d69786-ca5e-4b15-58bd-c58e051c9a12-b0b4a4fa9b1b08dd6de24a84f3a99b82","tags":{"Name":"mySG","ernest.service":"azure-security-group"}},{"_action":"create","_component":"virtual_network","_component_id":"virtual_network::myNet","_provider":"azure","_state":"completed","address_space":["10.0.0.0/16"],"azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"datacenter_name":"","datacenter_region":"","datacenter_type":"","dns_server_names":null,"environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myNet","location":"eastus","name":"myNet","resource_group_name":"myRG","service":"68d69786-ca5e-4b15-58bd-c58e051c9a12-b0b4a4fa9b1b08dd6de24a84f3a99b82","subnets":[{"address_prefix":"10.0.0.0/24","name":"mySubnet","security_group":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mySG","security_group_name":"mySG"}],"tags":null},{"_action":"create","_component":"subnet","_component_id":"subnet::mySubnet","_provider":"azure","_state":"completed","address_prefix":"10.0.0.0/24","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"datacenter_name":"","datacenter_region":"","datacenter_type":"","environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myNet/subnets/mySubnet","ip_configurations":null,"name":"mySubnet","network_security_group":"mySG","network_security_group_id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mySG","resource_group_name":"myRG","route_table_id":"","service":"68d69786-ca5e-4b15-58bd-c58e051c9a12-b0b4a4fa9b1b08dd6de24a84f3a99b82","virtual_network_name":"myNet"},{"_action":"none","_component":"credentials","_component_id":"credentials::azure","_provider":"azure","_state":"waiting","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","name":"azure","region":"eastus"},{"_action":"create","_component":"security_group","_component_id":"security_group::mySG2","_provider":"azure","_state":"completed","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mySG2","location":"eastus","name":"mySG2","resource_group_name":"myRG","security_rules":[{"access":"Allow","description":"myRule","destination_address_prefix":"Internet","destination_port_range":"0-65535","direction":"Outbound","name":"myRule","priority":100,"protocol":"Tcp","source_address_prefix":"VirtualNetwork","source_port_range":"*"}],"service":"cef27857-5575-4e4b-6ef9-7412341e21ee-b0b4a4fa9b1b08dd6de24a84f3a99b82","tags":{"Name":"mySG2","ernest.service":"azure-security-group"}}],"changes":[{"_action":"create","_component":"subnet","_component_id":"subnet::mySubnet2","_provider":"azure","_state":"errored","address_prefix":"10.0.1.0/24","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","error":"Error creating the requested resource : network.SubnetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"LinkedInvalidPropertyId\" Message=\"Property id '$(components.#[_component_id=\\\"security_group::mySG2\\\"].id)' at path 'properties.networkSecurityGroup.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.\"","id":"","ip_configurations":null,"name":"mySubnet2","network_security_group":"mySG2","network_security_group_id":"$(components.#[_component_id=\"security_group::mySG2\"].id)","resource_group_name":"myRG","route_table_id":"","service":"cef27857-5575-4e4b-6ef9-7412341e21ee-b0b4a4fa9b1b08dd6de24a84f3a99b82","virtual_network_name":"myNet"},{"_action":"create","_component":"security_group","_component_id":"security_group::mySG2","_provider":"azure","_state":"completed","azure_client_id":"+Musr4LEIol0Vulg4PrXYTnzcp901Orwd/z75ROEJTZtGpUB3m3HCKSLOc3Fasi7iblaLnfiLNtd9yxT","azure_client_secret":"9XBaMPuV9c+YegIefJtmUvH5zDEuOtle0LzchXHeqpe3IfE+dJdjyvM//9r3EqDiLMXHZozDjTzfWBaUWSKbqlELtJ8=","azure_subscription_id":"xQZ4o9n4+pzv06LZImCqN0t1omJFU/f1CPn+F5XaPc4+xeZlYNeJ5z+qXWnMNWbiqqVbHSZR2m7sLPAh","azure_tenant_id":"Ga/N81dS8FlfOkGt1SqILj616tk3OqaSC6Lni+uNiZmur6bjm9/flk/xSrdr+tOs9sVjsqPjy2yg9cI7","components":null,"environment":"gFNFPBqcYzJ79F1EKXu2J/AlPkBEiV+ji02EvLQx","id":"/subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mySG2","location":"eastus","name":"mySG2","resource_group_name":"myRG","security_rules":[{"access":"Allow","description":"myRule","destination_address_prefix":"Internet","destination_port_range":"0-65535","direction":"Outbound","name":"myRule","priority":100,"protocol":"Tcp","source_address_prefix":"VirtualNetwork","source_port_range":"*"}],"service":"cef27857-5575-4e4b-6ef9-7412341e21ee-b0b4a4fa9b1b08dd6de24a84f3a99b82","tags":{"Name":"mySG2","ernest.service":"azure-security-group"}}],"edges":[{"source":"start","destination":"subnet::mySubnet2","length":1},{"source":"subnet::mySubnet2","destination":"end","length":1},{"source":"start","destination":"security_group::mySG2","length":1},{"source":"security_group::mySG2","destination":"end","length":1}]}
```
