### ISSUE TITLE
Error deleting Security Group and Virtual Network

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#499]
An error is reported when attempting to remove a Security Group and Virtual Network which are referenced to one another.

Applying:

```
name: azure-security-group
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    virtual_networks:
      - name: myNet
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: mySubnet
            address_prefix: 10.0.0.0/24
            security_group: mySG
          - name: mySubnet2
            address_prefix: 10.0.1.0/24
            security_group: mySG2

    security_groups:
      - name: mySG
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535
      - name: mySG2
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535
```

Followed by:

```
name: azure-security-group
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    virtual_networks:
      - name: myNet
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: mySubnet
            address_prefix: 10.0.0.0/24
            security_group: mySG
 
    security_groups:
      - name: mySG
        rules:
          - name: myRule
            description: myRule
            priority: 100
            direction: Outbound
            access: Allow
            protocol: Tcp
            source_address_prefix: VirtualNetwork
            source_port_range: '*'
            destination_address_prefix: Internet
            destination_port_range: 0-65535
```

Results in:

```
Applying your definition
 Deleted Subnet mySubnet2
   Address Prefix : 10.0.1.0/24
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myNet/subnets/mySubnet2
   Status : completed

Oops! Something went wrong. Please manually fix any errors shown above and re-apply your definition.
```

Looking in the Azure Portal `mySubnet2` is removed but `mySG2` remains. Reapplying the manifest again seems to solve the issue which leads me to think it's dependency related.
