### ISSUE TITLE
Storage Account replication type does not update

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#501]
When amending the replication type of a Storage Group Ernest reports a successful apply even though the replication type doesn't get updated.

Applying:

```
name: azure-storage-account
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    storage_accounts:
      - name: mystorager3labs
        account_type: Standard_LRS
        account_kind: Storage
        enable_blob_encryption: false
        containers:
          - name: mycontainer
            access_type: private
```

Followed by:

```
name: azure-storage-account
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    storage_accounts:
      - name: mystorager3labs
        account_type: Standard_GRS
        account_kind: Storage
        enable_blob_encryption: false
        containers:
          - name: mycontainer
            access_type: private
```
