### ISSUE TITLE
Load Balancer rules missing attributes

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#506]
The Load Balancer rule is created but no attributes are set (except Frontend IP).

Applying:

```
name: azure-load-balancer
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    loadbalancers:
      - name: myLB
        probes:
          - name: myProbe
            port: 80
            protocol: Http
            request_path: /
            interval: 15
            max_failures: 2
        backend_address_pools:
          - myPool1
        frontend_ip_configurations:
          - name: myVIP
            public_ip_address_allocation: static
            rules:
              - name: myRule
                protocol: Tcp
                frontend_port: 80
                backend_port: 80
                backend_address_pool: myPool1
                probe: myProbe
                load_distribution: Default
                idle_timeout: 30
                floating_ip: false
```

Results in:

```
Applying your definition
 Created Resource Group myRG
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG
   Status : completed
 Created Public IP myLB-myVIP
   IP : 
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/publicIPAddresses/myLB-myVIP
   Status : completed
 Created Loadbalancer myLB
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG/providers/Microsoft.Network/loadBalancers/myLB
   Status    : completed
SUCCESS: rules successfully applied
```

![Screenshot from 2017-05-22 12:56:40.png](https://zube.io/files/ernestio/bfee5e5d49fff94ddae3dea7b758af2d.png)
