### ISSUE TITLE
SQL Server missing dependency required by attribute

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#508]
The attribute `elastic_pool_name` within the `sql_servers` resource expects the elastic pool to already exist (which it does't). To resolve this we need to create a new resource for managing elastic pools (https://www.terraform.io/docs/providers/azurerm/r/sql_elasticpool.html).

When using this attribute in Ernest things still apply successfully, it just does nothing.

Test manifest:

```
---
name: azure-sql-server
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    sql_servers:
      - name: mysqlserverr3labs
        version: "12.0"
        administrator_login: sqladmin
        administrator_login_password: Password123!
        databases:
          - name: myDB
            max_size_bytes: "10737418240"
            create_mode: Default
            edition: Standard
            collation: SQL_LATIN1_GENERAL_CP1_CI_AS
            elastic_pool_name: myElasticPool
```
