### ISSUE TITLE
SQL Server tags not updated

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#509]
Tags are not being updated in the `sql_servers` resource (database level tags are fine).

Applying:

```
---
name: azure-sql-server
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    sql_servers:
      - name: mysqlserverr3labs
        version: "12.0"
        administrator_login: sqladmin
        administrator_login_password: Password123!
        databases:
          - name: myDB
            max_size_bytes: "10737418240"
            create_mode: Default
            edition: Standard
            collation: SQL_LATIN1_GENERAL_CP1_CI_AS
            requested_service_objective_name: S0
        tags:
          myTag: myValue
```

Followed by:

```
---
name: azure-sql-server
datacenter: azure

resource_groups:
  - name: myRG
    location: eastus

    sql_servers:
      - name: mysqlserverr3labs
        version: "12.0"
        administrator_login: sqladmin
        administrator_login_password: Password123!
        databases:
          - name: myDB
            max_size_bytes: "10737418240"
            create_mode: Default
            edition: Standard
            collation: SQL_LATIN1_GENERAL_CP1_CI_AS
            requested_service_objective_name: S0
        tags:
          myTagNew: myValueNew
```

Results in a successful apply but tags remain unchanged.
