### ISSUE TITLE
Remove requirement for count attribute in virtual machines

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#513]
From a user perspective it would be nice to not have to declare this for building single instances.

From this:

```
virtual_machines:
- name: myVM
  size: Standard_A0
  count: 1
  ...
```

To this:

```
virtual_machines:
- name: myVM
  size: Standard_A0
  ...
```
