### ISSUE TITLE
Missing CLI output 'Virtual Network -> Address Space'

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#517]
Address Space output under Virtual Networks doesn't output anything.

Applying:

```
---
name: azure-virtual-machine
datacenter: azure

resource_groups:
  - name: myRG5
    location: eastus

    virtual_networks:
      - name: myNet
        address_spaces:
          - 10.0.0.0/16
        subnets:
          - name: mySubnet
            address_prefix: 10.0.0.0/24
```

Outputs:

```
Created Virtual Network myNet
Address Space :
ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/myRG4/providers/Microsoft.Network/virtualNetworks/myNet
Status : completed
```

This should return the ranges for all created networks.
