### ISSUE TITLE
Azure policy `azure_sql_firewall_rule` results in apply with no output.

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#892]
Policy
```
describe azure_sql_firewall_rule('rule1').where(server_name == 'jasonr3labs') do
  it {should exist}
end
```
Output:
```
$ ernest env apply az.yml
$
```

**Comment by reidjc** [comment]
```
    sql_servers:
      - name: r3labspolicy
        version: "12.0"
        administrator_login: xxxxxxxxxx
        administrator_login_password: yyyyyyyyyy
        databases:
          - name: mydb
            create_mode: Default
            edition: Standard
        rules:
          - name: rule1
            start_ip_address: 10.0.17.62
            end_ip_address: 10.0.17.63
```
