### ISSUE TITLE
Azure `azure_sql_firewall_rule` `location` error

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#895]
YAML
```
    sql_servers:
      - name: jasonr3labs
        version: "12.0"
        administrator_login: administrator
        administrator_login_password: xxxxxxxx
        databases:
          - name: mydb
            create_mode: Default
            edition: Standard
        rules:
          - name: rule1
            start_ip_address: 10.0.17.62
            end_ip_address: 10.0.17.63
```

Policy
```
describe azure_sql_firewall_rule('rule1').where{server_name == 'jasonr3labs'} do
  it {should exist}
  its('location'){ should be 'westeurope'}
  its('resource_group') { should be 'az-test'}
  its('start_ip_address') { should be '10.0.17.62' }
  its('end_ip_address') { should be '10.0.17.63' }
end
```

Output
```
    ✘ Azure SQL Firewall Rule rule1
      ✔ should exist
      ✘ location
        undefined method `location' for Azure SQL Firewall Rule rule1:#<Class:0x0000558fffb38208>
      ✔ resource_group should be "az-test"
      ✔ start_ip_address should be "10.0.17.62"
      ✔ end_ip_address should be "10.0.17.63"
```
